name: Lint

on:
  push:
    branches:
      - main

jobs:
  lint-commit-msg:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install deps
        run: bun install
      - name: Lint commit message
        run: bunx commitlint --last --verbose

  lint-code:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install deps
        run: bun install
      - name: Lint code
        run: bun run lint
